---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: labmon-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: labmon-cni
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: labmon-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      containers:
      - name: labmon-cni
        image: fsedano/labmon-cni:latest
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: labmon-cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: labmon-cnibin
          hostPath:
            path: /opt/cni/bin
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: qinq-conf
spec:
  config: '{ "cniVersion": "0.3.1", "name": "labmon-net", "type": "labmon.py" }'

## type=exe name
## /tmp/fran-multus-conf # cp * /host/etc/cni/net.d/